language: Swift

xcode_project: Product\ Hunt.xcodeproj
xcode_scheme: Debug
osx_image: xcode10
os: osx

before_install:

- export LANG=en_US.UTF-8
- gem install cocoapods --quiet
- cp Source/Config/Keys-Example.xcconfig Source/Config/Keys.xcconfig

script:

- xctool -workspace Product\ Hunt.xcworkspace -scheme Debug -sdk macosx clean test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
